#!/bin/sh

sed -i '/application\/pdf/d' /usr/share/applications/mimeinfo.cache
sed -i '/application\/pdf/d' /usr/share/applications/mimeinfo.cache
sed -i '/application\/pdf/d' /usr/share/applications/mimeinfo.cache

for item in $(ls /usr/share/applications/)
do
	if [ $item != 'mimeinfo.cache' ] 
	then
		#echo $item
		sed -i 's/application\/pdf;//g' /usr/share/applications/$item
		sed -i 's/application\/pdf;//g' /usr/share/applications/$item
		sed -i 's/application\/pdf;//g' /usr/share/applications/$item
	fi
done


exit 0
